### ISSUE TITLE
Regular Expressions support for BLACKLISTED_DATABASES

### ISSUE THREAD

**Issue by fredj** [camptocamp/docker-postgres-backup-to-s3#4]
The `BLACKLISTED_DATABASES` can only contain a list of comma separated names; it would be nice to be able to use a regular expression. For example, for the schweimobil configuration, the variable would be something like:
```
'.*_backup_?|rdsadmin|template?|postgres'
```
It should be simple to have this by changing the sql select to:
```sql
SELECT datname FROM pg_database WHERE datname !~ ($blacklisted_databases)
```

postgresql ref:
https://www.postgresql.org/docs/current/static/functions-matching.html#FUNCTIONS-POSIX-REGEXP

**Comment by fredj** [comment]
and we can probably always ignore the templates databases:
```sql
SELECT datname FROM pg_database WHERE datistemplate IS FALSE AND datname !~ ($blacklisted_databases)
```

**Comment by cryptobioz** [comment]
Great idea, thanks @fredj!

**Comment by fredj** [comment]
Thanks @cryptobioz !
